name: Deploy to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup SSH key from GitHub Secret
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Test SSH connection
      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connected to EC2 & whoami"

      # Step 4: Deploy application files
      - name: Copy files to Windows EC2
        run: |
          scp -i ~/.ssh/ec2_key.pem -r ./Build/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/C:/automation_Jenkins/Build/

      # Step 5: Run deployment commands remotely
      - name: Run deployment on EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Starting deployment..."
            
            # Navigate to deployment directory
            cd C:/automation_Jenkins

            # Run PowerShell deployment script
            powershell -ExecutionPolicy Bypass -File deploy.ps1

            echo "Deployment completed!"
EOF
