name: React CI/CD + Full Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Copy all files to Windows EC2
      env:
        EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "Copying all files to Windows EC2..."
        sshpass -p "$EC2_PASSWORD" scp -o StrictHostKeyChecking=no -r ./* administrator@$EC2_HOST:C:/inetpub/

    - name: Run deployment script on Windows EC2
      env:
        EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "Running deploy.ps1 on Windows EC2..."
        sshpass -p "$EC2_PASSWORD" ssh -o StrictHostKeyChecking=no administrator@$EC2_HOST "
          powershell -ExecutionPolicy Bypass -File C:/inetpub/deploy.ps1
        "
